module.exports = {
  $activity: "Return the Author Actvity;$activity or $activity[$userID]",
  $addField: "Changes the Field of MessageEmbed;$addField[text;image url]",
  $author: "Changes the Author of MessageEmbed;$author[text;image url]",
  $authorID: `Returns the Author ID of Message or Reaction;$authorID`,
  $authorMessage: `Returns the Author ID of Message;$authorMessage`,
  $boolean: `Returns boolean for provided data;$boolean[data]`,
  $botPing: "Return the Message Ping",
  $channel: `Compacted Channel Function
  Available options: 
  use, id, name, guild, created, type, category, position, rawPosition.;$channel[channelID;option]`,
  $channelName: `Returns the Channel Name of ChannelID;$channelName[channelID]`,
  $channelID: "Returns the Channel ID of Message;$channelID",
  $clientID: `Returns the User ID of used Client;$clientID`,
  $color: "Changes the Color of MessageEmbed;$color[Hex / String / Number]",
  $date: `Returns the <duration> of <ms>;$date[MS / Date String / ISO String / JS Convertable Date;duration (year/month/day/hour/minute/second)]`,
  $dbPing: `Return's the Database Ping from Client`,
  $description: `Changes the Description of MessageEmbed;$description[text]`,
  $divide: "Divide given values;$divide[1;2;3;...]",
  $discriminator: "Returns the Discriminator of user ID;$discriminator or $discriminator[userID]",
  $escapeCharacters: "Escape the characters for Functions to not identify it as a separator;$escapeCharacters[text]",
  $eval: "Evaluates given Snippet of code;$eval[code]",
  $footer: "Changes the Footer of MessageEmbed;$footer[text;image url]",
  $log: "Print message to REPL;$log[message]",
  $message: `Returns the contents of message, if number is provided, it return the index of argument.;$message or $message[number] or $message[<|>]`,
  $onlyForIDs: "Restrict Access to given User ID's;$onlyForIDs[userID;userID;...;error message]",
  $onlyIf: `Blocks code from running if condition does not meet the requirements.
  Conditions have operators as such Equal (==), Not Equal (!=), Greater than (>), Less than (<), Greater than or Equal to (>=), Less than or Equal to (<=).
  $onlyIf also reacts to Booleans, "true" is enough as condition.
  ;$onlyIf[condition;error message]`,
  $mathPI: "Returns the mathematical value of 𝜋 (PI);$mathPI",
  $modulo: "Modulo given values;$modulo[1;2;3;...]",
  $multi: "Multiply given values;$multi[1;2;3;...]",
  $ping: "Returns the Client Ping",
  $presence: "Return the Author Presence;$presence or $presence[userID]",
  $packageVersion: "Return the package version",
  $parseTime: "Sets human readable time into milliseconds;$parseTime[ms]",
  $ram: `Return the Ram Usage`,
  $reactionEmoji: `Returns the ID of Emoji from Reaction event, only works in MessageReaction events.;$reactionEmoji`,
  $reboot: `Reboot the Client`,
  $replaceText: "Replaces <how many> amount of <target> to <replacement> in the <text>. <how many> is default to -1;$replaceText[text;target;replacement;how many]",
  $round: "Returns a rounded version of number;$round[number]",
  $setStatus: "Set a Status for the Client;$setStatus[text;type;status]",
  $thumbnail: "Changes the Thumbnail of MessageEmbed;$thumbnail[image url]",
  $timestamp: "Returns the timestamp of date;$timestamp or $timestamp[ MS / Date String / ISO String / JavaScript convertable Date]",
  $title: "Changes the Title of MessageEmbed;$title[text]",
  $uptime: "Return the uptime of the Client in milliseconds;$uptime",
  $useChannel: "Use given ID as message Channel;$useChannel[channel ID]",
  $userAvatar: "Return the Author UserAvatar image url;$userAvatar or $userAvatar[userID]",
  $username: "Returns the Username of user ID;$username or $username[userID]",
  $userTag: "Returns the UserTag of user ID;$usertag or $usertag[userID]",
  $sub: "Subtract given values;$sub[1;2;3;...]",
  $sum: "Sumarize given values;$sum[1;2;3;...]",
}